// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: allowed_users.sql

package sqlc

import (
	"context"
)

const isAllowedUser = `-- name: IsAllowedUser :one
SELECT EXISTS (
    SELECT 1
    FROM allowed_users
    WHERE telegram_user_id = $1
        AND is_active = TRUE
)
`

func (q *Queries) IsAllowedUser(ctx context.Context, telegramUserID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isAllowedUser, telegramUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAllowedUsers = `-- name: ListAllowedUsers :many
SELECT telegram_user_id, role, is_active, created_at, updated_at FROM allowed_users
    ORDER BY updated_at
`

func (q *Queries) ListAllowedUsers(ctx context.Context) ([]AllowedUser, error) {
	rows, err := q.db.Query(ctx, listAllowedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllowedUser{}
	for rows.Next() {
		var i AllowedUser
		if err := rows.Scan(
			&i.TelegramUserID,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAllowedUser = `-- name: UpsertAllowedUser :one
INSERT INTO allowed_users (
    telegram_user_id,
    role
) VALUES (
    $1,
    $2
)
ON CONFLICT (telegram_user_id) DO UPDATE SET
    role = EXCLUDED.role,
    is_active = TRUE,
    updated_at = NOW()
RETURNING telegram_user_id, role, is_active, created_at, updated_at
`

type UpsertAllowedUserParams struct {
	TelegramUserID int64
	Role           string
}

func (q *Queries) UpsertAllowedUser(ctx context.Context, arg UpsertAllowedUserParams) (AllowedUser, error) {
	row := q.db.QueryRow(ctx, upsertAllowedUser, arg.TelegramUserID, arg.Role)
	var i AllowedUser
	err := row.Scan(
		&i.TelegramUserID,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
